module.exports = {
	'for-direction': 'warn',
	'getter-return': 'warn',
	'no-async-promise-executor': 'warn',
	'no-await-in-loop': 'warn',
	'no-compare-neg-zero': 'warn',
	'no-cond-assign': ['warn', 'except-parens'],
	'no-console': 'warn',
	'no-constant-condition': 'warn',
	'no-control-regex': 'warn',
	'no-debugger': 'warn',
	'no-dupe-args': 'warn',
	'no-dupe-keys': 'warn',
	'no-duplicate-case': 'warn',
	'no-empty': 'warn',
	'no-empty-character-class': 'warn',
	'no-ex-assign': 'warn',
	'no-extra-boolean-cast': 'warn',
	'no-extra-parens': ['warn', 'all', {
		nestedBinaryExpressions: false,
		returnAssign: false,
		conditionalAssign: false,
		ignoreJSX: 'multi-line',
	}],
	'no-extra-semi': 'warn',
	'no-func-assign': 'warn',
	'no-invalid-regexp': 'warn',
	'no-irregular-whitespace': 'warn',
	'no-misleading-character-class': 'warn',
	'no-obj-calls': 'warn',
	'no-regex-spaces': 'warn',
	'no-sparse-arrays': 'warn',
	'no-template-curly-in-string': 'warn',
	'no-unexpected-multiline': 'warn',
	'no-unreachable': 'warn',
	'no-unsafe-finally': 'warn',
	'no-unsafe-negation': 'warn',
	'require-atomic-updates': 'warn',
	'use-isnan': 'warn',
	'valid-typeof': 'warn',
}
