module.exports = {
	'arrow-body-style': ['warn', 'as-needed'],
	'arrow-parens': ['warn', 'as-needed', { requireForBlockBody: true }],
	'arrow-spacing': 'warn',
	'constructor-super': 'error',
	'generator-star-spacing': 'warn',
	'no-class-assign': 'warn',
	'no-confusing-arrow': 'off',
	'no-const-assign': 'error',
	'no-dupe-class-members': 'warn',
	'no-duplicate-imports': 'warn',
	'no-new-symbol': 'warn',
	'no-this-before-super': 'error',
	'no-useless-computed-key': 'warn',
	'no-useless-constructor': 'warn',
	'no-useless-rename': 'warn',
	'no-var': 'warn',
	'object-shorthand': 'warn',
	'prefer-arrow-callback': ['warn', { allowNamedFunctions: true }],
	'prefer-const': 'warn',
	'prefer-destructuring': 'warn',
	'prefer-numeric-literals': 'off',
	'prefer-rest-params': 'off',
	'prefer-spread': 'off',
	'prefer-template': 'warn',
	'require-yield': 'warn',
	'rest-spread-spacing': 'warn',
	'symbol-description': 'off',
	'template-curly-spacing': ['warn', 'never'],
	'yield-star-spacing': 'off',
}
