module.exports = {
	'react/jsx-boolean-value': ['warn', 'never'],
	'react/jsx-child-element-spacing': 'off',
	'react/jsx-closing-bracket-location': ['warn', 'line-aligned'],
	'react/jsx-closing-tag-location': 'off',
	'react/jsx-curly-spacing': ['warn', { when: 'never' }],
	'react/jsx-equals-spacing': ['warn', 'never'],
	'react/jsx-filename-extension': 'off',
	'react/jsx-first-prop-new-line': ['warn', 'multiline-multiprop'],
	'react/jsx-handler-names': ['warn', {
		eventHandlerPrefix: 'handle',
		eventHandlerPropPrefix: 'on',
	}],
	'react/jsx-indent': ['warn', 'tab'],
	'react/jsx-indent-props': ['warn', 'tab'],
	'react/jsx-key': 'warn',
	'react/jsx-max-depth': 'off',
	'react/jsx-max-props-per-line': ['warn', { maximum: 1, when: 'multiline' }],
	'react/jsx-no-bind': 'warn',
	'react/jsx-no-comment-textnodes': 'warn',
	'react/jsx-no-duplicate-props': 'warn',
	'react/jsx-no-literals': 'off',
	'react/jsx-no-target-blank': 'warn',
	'react/jsx-no-undef': 'error',
	'react/jsx-one-expression-per-line': ['warn', { allow: 'single-child' }],
	'react/jsx-curly-brace-presence': ['warn', { props: 'never', children: 'ignore' }],
	'react/jsx-pascal-case': 'warn',
	'react/jsx-props-no-multi-spaces': 'warn',
	'react/jsx-sort-default-props': 'off',
	'react/jsx-sort-props': ['warn', {
		callbacksLast: true,
		shorthandFirst: true,
		shorthandLast: false,
		ignoreCase: false,
		noSortAlphabetically: true,
		reservedFirst: true,
	}],
	'react/jsx-tag-spacing': ['warn', {
		closingSlash: 'never',
		beforeSelfClosing: 'always',
		afterOpening: 'never',
		beforeClosing: 'never',
	}],
	'react/jsx-uses-react': 'warn',
	'react/jsx-uses-vars': 'warn',
	'react/jsx-wrap-multilines': 'off',
}
